export const ItemActionTypes = {
  ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  REMOVE_ITEM_SUCCESS: 'REMOVE_ITEM_SUCCESS',
  UPDATE_ITEM_COUNT_SUCCESS: 'UPDATE_ITEM_COUNT_SUCCESS',

  REQUEST_STARTED: 'REQUEST_STARTED',
  REQUEST_FAILURE: 'REQUEST_FAILURE',
};